// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedPlaceholder: typeof import('./src/components/AnimatedPlaceholder.vue')['default']
    AsyncWordCardView: typeof import('./src/components/AsyncWordCardView.vue')['default']
    AsyncWordView: typeof import('./src/components/AsyncWordView.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/select/select.vue')['default']
    SelectBar: typeof import('./src/components/SelectBar.vue')['default']
    SelectItem: typeof import('./src/components/select/select-item.vue')['default']
    SiteNavigation: typeof import('./src/components/SiteNavigation.vue')['default']
    VarRadio: typeof import('@varlet/ui')['_RadioComponent']
    VarRadioGroup: typeof import('@varlet/ui')['_RadioGroupComponent']
    VarRate: typeof import('@varlet/ui')['_RateComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    WordCard: typeof import('./src/components/WordCard.vue')['default']
    WordCardSkeleton: typeof import('./src/components/WordCardSkeleton.vue')['default']
    WordList: typeof import('./src/components/WordList.vue')['default']
    WordViewSkeleton: typeof import('./src/components/WordViewSkeleton.vue')['default']
  }
}
