// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedPlaceholder: typeof import('./../components/AnimatedPlaceholder.vue')['default']
    AsyncWordCardView: typeof import('./../components/AsyncWordCardView.vue')['default']
    AsyncWordView: typeof import('./../components/AsyncWordView.vue')['default']
    BaseModal: typeof import('./../components/BaseModal.vue')['default']
    Icon: typeof import("./../components/Icon/src/Icon.vue")["default"]
    KeepAliveRouterView: typeof import("./../components/KeepAliveRouterView/src/KeepAliveRouterView.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/select/select.vue')['default']
    SelectBar: typeof import('./../components/SelectBar.vue')['default']
    SelectItem: typeof import('./../components/select/select-item.vue')['default']
    SiteNavigation: typeof import('./../components/SiteNavigation.vue')['default']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WordCard: typeof import('./../components/WordCard.vue')['default']
    WordCardSkeleton: typeof import('./../components/WordCardSkeleton.vue')['default']
    WordList: typeof import('./../components/WordList.vue')['default']
    WordViewSkeleton: typeof import('./../components/WordViewSkeleton.vue')['default']
  }
}
