// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedPlaceholder: typeof import('./../components/backup/AnimatedPlaceholder.vue')['default']
    AsyncWordCardView: typeof import('./../components/backup/AsyncWordCardView.vue')['default']
    AsyncWordView: typeof import('./../components/backup/AsyncWordView.vue')['default']
    BaseModal: typeof import('./../components/backup/BaseModal.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    KeepAliveRouterView: typeof import('./../components/KeepAliveRouterView/src/KeepAliveRouterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/backup/select/select.vue')['default']
    SelectBar: typeof import('./../components/backup/SelectBar.vue')['default']
    SelectItem: typeof import('./../components/backup/select/select-item.vue')['default']
    SiteNavigation: typeof import('./../components/backup/SiteNavigation.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WordCard: typeof import('./../components/backup/WordCard.vue')['default']
    WordCardSkeleton: typeof import('./../components/backup/WordCardSkeleton.vue')['default']
    WordList: typeof import('./../components/backup/WordList.vue')['default']
    WordViewSkeleton: typeof import('./../components/backup/WordViewSkeleton.vue')['default']
  }
}
